### ISSUE TITLE
Button on home page Wrong syntax

### ISSUE THREAD

**Issue by Marfjeh** [Cp-022/ALA-Servicedesk#2]
* File INDEX.HTML
```
<button id = "klacht" class = "button"><a href = "klacht.html">Klacht</a></button> 
```
This is not working in firefox dont know about chrome but, you need to use javascript and not a hyperlink in a button. you can use javascript for example:
```
<button id ="klacht" class ="button" onclick="window.location.href='klacht.html'">Klacht</button>
```

window.location.href is javascript so you can use Javascript on Onclick tags in buttons.
Just letting you know.

**Comment by Cp-022** [comment]
Somehow didnt work on firefox but it did on chrome, added it in could you recheck?

**Comment by Marfjeh** [comment]
after rechecking in firefox it didnt work. Anyways i saw you corrected the problem with push: <a href="https://github.com/Cp-022/ALA-Servicedesk/commit/65a16a52bda744ee9b5d3c6325424b7578b20f4d">65a16a5</a>. after testing with firefox it worked. gj.

just a tip, after you made a change in css or html, check with 3 browsers or more, Firefox, Chrome and IE/Edge (edge is more like chrome but there's some things different in edge) You can't make a website just for one browser and force people to use that browser.
